name: tienda_online_reina
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.8.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  
  # Dependencias de Utilidad requeridas
  collection: ^1.17.2
  intl: ^0.18.1 
  
  # Dependencias de Firebase
  firebase_core: ^2.24.2  # Mínimo para inicializar Firebase
  cloud_firestore: ^4.13.6 # Para la base de datos (Órdenes)
  firebase_auth: ^4.15.2  # Para la autenticación (Usuarios)

  shared_preferences: ^2.2.2
    
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  # Directorio de Assets (imágenes)
  assets: 
    - assets/images/