// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpm8SE9u8I1ztqgDsFmPWjsSO-3F0lEaE',
    appId: '1:63355619547:web:63457416a1685060ed24fe',
    messagingSenderId: '63355619547',
    projectId: 'tiendareinaapp',
    authDomain: 'tiendareinaapp.firebaseapp.com',
    storageBucket: 'tiendareinaapp.firebasestorage.app',
    measurementId: 'G-5X0MBLKPSE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMQ8eyjV2nR2CoGLE8u_0gDmhHC1EFR1E',
    appId: '1:63355619547:android:e02dc36aafde05d8ed24fe',
    messagingSenderId: '63355619547',
    projectId: 'tiendareinaapp',
    storageBucket: 'tiendareinaapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJGWw3u1Y9pn9ldO93-RxftyNfpJ1tyEw',
    appId: '1:63355619547:ios:e74fe15938506507ed24fe',
    messagingSenderId: '63355619547',
    projectId: 'tiendareinaapp',
    storageBucket: 'tiendareinaapp.firebasestorage.app',
    iosBundleId: 'com.example.tiendaOnlineReina',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJGWw3u1Y9pn9ldO93-RxftyNfpJ1tyEw',
    appId: '1:63355619547:ios:e74fe15938506507ed24fe',
    messagingSenderId: '63355619547',
    projectId: 'tiendareinaapp',
    storageBucket: 'tiendareinaapp.firebasestorage.app',
    iosBundleId: 'com.example.tiendaOnlineReina',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpm8SE9u8I1ztqgDsFmPWjsSO-3F0lEaE',
    appId: '1:63355619547:web:f7599ec2333a47d5ed24fe',
    messagingSenderId: '63355619547',
    projectId: 'tiendareinaapp',
    authDomain: 'tiendareinaapp.firebaseapp.com',
    storageBucket: 'tiendareinaapp.firebasestorage.app',
    measurementId: 'G-67V3YBYBZ1',
  );
}
